columns:
  time: object
  latitude: float64
  longitude: float64
  depth: float64
  mag: float64
  magType: object
  nst: float64
  gap: float64
  dmin: float64
  rms: float64
  net: object
  id: object
  updated: object
  place: object
target_column: mag
